# miwidothttp Configuration

[server]
http_port = 8080
https_port = 8443
bind_address = "0.0.0.0"
static_dir = "./static"

[ssl]
enabled = true
cert_path = "./certs/server.crt"
key_path = "./certs/server.key"

# Backend configurations for virtual hosts
# Example: Forward requests for api.example.com to localhost:3000
[backends."api.example.com"]
target = "http://localhost:3000"
health_check = "/health"

# Example: Forward requests for app.example.com to localhost:4000
[backends."app.example.com"]
target = "http://localhost:4000"

# To test locally, add these to /etc/hosts:
# 127.0.0.1 api.example.com
# 127.0.0.1 app.example.com
