version: '3.8'

services:
  miwidothttp:
    build: .
    ports:
      - "9001:9001"
      - "8443:8443"
    volumes:
      - ./config.toml:/etc/miwidothttp/config.toml:ro
      - ./static:/app/static:ro
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro

  benchmark:
    image: williamyeh/wrk
    profiles: ["benchmark"]
    depends_on:
      - miwidothttp
      - nginx
    command: >
      sh -c "
        echo 'Waiting for servers to start...';
        sleep 5;
        echo 'Testing miwidothttp...';
        wrk -t4 -c100 -d10s --latency http://miwidothttp:9001/index.html;
        echo '';
        echo 'Testing nginx...';
        wrk -t4 -c100 -d10s --latency http://nginx/index.html
      "